[profile.default]
src = "_contracts"
out = "out"
libs = ["lib"]
test = "tests"
script = "scripts"

optimizer = true
optimizer_runs = 200

verbosity = 3

fs_permissions = [{ access = "read", path = "./"}]